config/routes.rb
Rails.application.routes.draw do
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  root "home#index"
  resources :chats, only: [:show, :new, :create] do
    resources :messages, only: [:new, :create]
  end
  resources :user_chats, only: [:destroy]
end

app/views/shared/_alerts.html.erb
<% if notice %>
  <div class="flex flex-col gap-1 mt-3">
    <div class="alert alert-info shadow-lg flex-col text-sm p-3 rounded-lg">
      <%= notice %>
    </div>
  </div>
<% end %>
<% if alert %>
  <div class="flex flex-col gap-1 mt-3">
    <div class="alert alert-error shadow-lg flex-col text-sm p-3 rounded-lg">
      <%= alert %>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar bg-base-100">
  <div class="navbar-start">
    <div class="dropdown">
      <div tabindex="0" role="button" class="btn btn-ghost btn-circle">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7" /></svg>
      </div>
      <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow rounded-box w-52 bg-primary">
        <li>
          <%= link_to "Dashboard", root_path %>
        </li>
        <p class="text-xs mt-3 opacity-30">Login and verification</p>
        <hr class="opacity-30"/>
        <li>
          <%= link_to "Change password", edit_password_path %>
        </li>
        <li>
          <%= link_to "Change email address", edit_identity_email_path %>
        </li>
        <p class="text-xs mt-3 opacity-30">Access history</p>
        <hr class="opacity-30"/>
        <li>
          <%= link_to "Devices & Sessions", sessions_path %>
        </li>

        <br>
        <hr class="opacity-30"/>
        <li>
          <%= button_to "Log out", Current.session, method: :delete %>
        </li>
      </ul>
    </div>
  </div>
  <div class="navbar-center">
    <% if @chat.present? %>
      <%= @chat.name %>
    <% else %>
      <%= link_to new_chat_path, data: { turbo_frame: "modal" }, class: "btn btn-ghost text-xl" do %>
        <span class="text-base sm:text-sm">Start Conversation</span>
      <% end %>
    <% end %>
  </div>
  <div class="navbar-end">
    <button class="btn btn-ghost btn-circle">
      <div class="indicator">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" /></svg>
      </div>
    </button>
  </div>
</div>