config/routes.rb
Rails.application.routes.draw do
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  root "home#index"
  resources :chats, only: [:show, :new, :create] do
    resources :messages, only: [:new, :create]
  end
  resources :user_chats, only: [:destroy]
end

app/models/chat.rb
# == Schema Information
#
# Table name: chats
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Model representing a chat room where users can exchange messages.
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :user_chats, dependent: :destroy
  has_many :users, through: :user_chats

  accepts_nested_attributes_for :user_chats, :messages

  broadcasts_to ->(chat) { "chats" }, inserts_by: :prepend

  validates :name, presence: true

  scope :with_users, -> { includes(:users) }
  scope :ordered, -> { order(created_at: :desc) }
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show]

  def show
    @user_chat = @chat.user_chats.find_by(user_id: Current.user)

    redirect_to root_path unless @user_chat
  end

  def new
    @chat = Current.user.chats.new
    @chat.messages.build
    @chat.user_chats.build(user: Current.user)
  end

  def create
    @chat = Current.user.chats.new(chat_params)
    @chat.user_chats.build(user: Current.user)

    if @chat.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def chat_params
    params.require(:chat).permit(
      :name,
      messages_attributes: [:content, :user_id],
      user_chats_attributes: [:id, :user_id]
    )
  end

  def set_chat
    @chat = Chat.find(params[:id])
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_chat.html.erb
<%= turbo_frame_tag dom_id(chat) do %>
  <%= link_to chat_path(chat), data: { turbo: false }, class: 'card bg-primary text-primary-content mb-2' do %>
    <div class="card-body p-3">
      <h2 class="card-title"><%= chat.name %></h2>
      <p class="text-xs" >
        <% chat.users.each do |user| %>
          <%= user.email %>
        <% end %>
      </p>
    </div>
  <% end %>
<% end %>

app/views/chats/_form.html.erb
<div class="w-full rounded-lg py-2 pb-4 rounded-b-none">
  <%= form_for chat, class: "relative w-full" do |form| %>
    <% if form.object.errors.any? %>
      <div class="flex flex-col gap-1 mt-3">
        <% form.object.errors.each do |error| %>
          <div class="alert alert-error shadow-lg flex-col text-sm p-3 rounded-lg">
            <%= error.full_message %>
          </div>
        <% end %>
      </div>
    <% end %>
    <%= form.label :name, class: "label" do %>
      Name
    <% end %>
    <%= form.text_field :name, placeholder: "Topic", class: "shadow input w-full placeholder:text-grey-100 text-grey-100" %>

    <%= form.fields_for :user_chats do |user_chats_form| %>
      <div data-controller="multiple-select">
        <%= user_chats_form.label :user_id, class: "label" do %>
          Add Users
        <% end %>
        <%= user_chats_form.collection_select :user_id,
          User.all.where.not(id: Current.user.id),
          :id,
          :email,
          {
            include_hidden: false,
            prompt: "Select at least one user"
          },
          {
            multiple: true,
            data: { "multiple-select-target": "select" },
            name: 'chat[user_chats_attributes][][user_id]'
          }
        %>
      </div>
    <% end %>

    <div class="w-full flex gap-3 mt-5">
      <%= form.fields_for :messages do |message_form| %>
        <%= message_form.text_field :content, placeholder: "Hello!", class: "shadow input w-full placeholder:text-grey-100 text-grey-100" %>
        <%= message_form.hidden_field :user_id, value: Current.user.id %>
      <% end %>
    </div>

    <div class="w-full flex justify-end mt-3">
      <%= form.button(type: 'submit', class: "shadow-lg btn btn-dark") do %>
        <svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M15.9472 9.3944C16.286 9.225 16.5 8.8788 16.5 8.5C16.5 8.12124 16.286 7.77498 15.9472 7.60558L1.9472 0.605582C1.5925 0.428232 1.1665 0.477242 0.861401 0.730502C0.556201 0.983762 0.429501 1.39342 0.5385 1.77473L1.967 6.77472C2.0897 7.20402 2.4821 7.5 2.9286 7.5H7.5C8.0523 7.5 8.5 7.94772 8.5 8.5C8.5 9.0523 8.0523 9.5 7.5 9.5L2.9286 9.5C2.4821 9.5 2.0897 9.796 1.967 10.2253L0.5385 15.2253C0.429501 15.6066 0.556201 16.0163 0.861401 16.2695C1.1665 16.5228 1.5925 16.5718 1.9472 16.3944L15.9472 9.3944Z" fill="white"/>
        </svg>
      <% end %>
    </div>
  <% end %>
</div>

app/views/chats/create.turbo_stream.erb
<%= turbo_stream.update "modal" do %>
<% end %>

app/views/chats/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <dialog id="new_credential" class="modal" data-controller="modal" data-modal-target="modal">
    <div class="modal-box bg-primary text-gray-100 rounded-lg">
      <div class="flex justify-between">
        <h3 class="font-bold text-lg">New conversation</h3>
        <form method="dialog">
          <button class="btn btn-circle btn-outline btn-sm text-gray-100">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>
          </button>
        </form>
      </div>
      <%= render partial: "chats/form", locals: { chat: @chat } %>
    </div>
  </dialog>
<% end %>

app/views/chats/show.html.erb
<section>
  <%= turbo_frame_tag dom_id(@chat, :form) do %>
    <%= render partial: "messages/form", locals: { chat: @chat, message: @chat.messages.new } %>
  <% end %>

  <%= turbo_stream_from dom_id(@chat, :messages) %>

  <%= turbo_frame_tag dom_id(@chat, :messages) do %>
    <% @chat.messages.ordered.with_user.each do |message| %>
      <%= render partial: 'messages/message', locals: { message: message } %>
    <% end %>
  <% end %>
</section>

<div class="fixed bottom-4 left-4">
  <%= button_to 'Leave Conversation', user_chat_path(@user_chat),
    method: :delete,
    data: { turbo: false },
    class: 'bg-gray-100 hover:bg-gray-200 text-red-500 py-2 px-4 rounded-full shadow-lg text-xs'
  %>
</div>